name = "server-sg" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"
[[routes]]
pattern = "sg1.darmocloud.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.darmocloud.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.darmocloud.my.id"
custom_domain = true

[vars]
UUID = "6a194259-4c51-4621-bbe5-5de7a18eee39"
